language: node_js
node_js:
  - '7'
  - '6'

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    template:
      - "%{repository_slug}@%{branch} (%{commit}): %{result} in %{duration}"
      - "%{build_url}"
    rooms:
      secure: bLLnAsAqD2+eEDpwHFO7ViStHVFLcNNiliRE1o4fjFxXzEAs25iwJZN0qreFpVbAaInyFy67MZKqLRf10e8c1xofOhJUtTwZuj7Wz/jvtAWyXAuB/70r/WKbkN/d2EsJ8p5BQG3o6uskVFibRuRSGjDRqggNdvLO82zrLvyv4Tn638GZgW2bpfX7Q47RJqNDIyImORDr0rBzbaMJmkzgt3bFMsUf8QrnV1kuYqxFAFTN4jzgK4PPRkltUnuR6PTMZOE/ppBVhMtLYrKmqmlvUoS07KqVYMuckGFXIzgPZ0yvHtZEXtY5T4RBvEuvHROzwf41SAs9HBbtYlbBsSm07mjVH/1GWYCAvgZT8ImR697kzW6dFgeSX5ZIY22QHLB6wtb3uozFjmlyF0g8NMKxCcZfqeyo5X6WRgNb2v5bpfLYzV05b/vaJ7T+ezzCZEjGlcGS7rhCN1NLSKAGzK3PGQJXCJn7hqKdJYiAiwyQsogOokvzbsDwO+tfTdhx0HobWcW/ushLfAt9Bbv9AhG4fGRV/ePvkgMgr4eJHlR44ntZpbM+QwnXuS10UZreyeOmEBODtBEKMS7aHsqKKIXyWuY72AvR+CN24jZkPQMHJlD4PIVblWY1yRIATjdT/QjYNacaaFX38fctVK4AwVeBVRKQik1ExeiNFL62OlX61bc=
    on_success: change
    on_failure: always

env:
  global:
    secure: UyQtn/yzTOY4Z51ug6gQle0QLT/+XB/C0wojRsiU7SyUKk40G8spFXRNRn/uWi+Xg/ZDHvMJ91JYudGA3Etgu1d/f2sZdaNg/M0b5BT/78wDZDom8eoTM8mtBKwTHPT+5lwgwxkR+sj9cXsKUtVizGIgpzq89LaTAexdg8+3r+mefBacsuHiqT/VwD40lcS55twRRUZQS1J5sz3TOdN82VfidCyU11yPrdNl5qrPlnGy+Fq7jKXBa0VYV8DMyrlmbYiqX/gLXomNESOgZhqaJ4uPF057PrI6Uxs7y1Eq0AQ8qqtdqp1sKkkf0zq6hryTOizGdv6F3xQcd969K0WZegxpuLSBG+lIe+R7ICuGX7pofRbx+omRB0x/gNEAMs38vki+OC9cjl61GZksfJ4ILxJzrqk+S6t35W7BPXuH6bw52tyql+/p/LZDMbakUMWUzAzI5pmR9q9eX7HuvThnvLH805yElgOfJWA5q313VCerMe5Y0QjQPzRUQtQgeteyZQ/lcmChLbKCaHH+FQQI1UN55nHKd8VRr910Iq7bCEy26rUWujeRCt/msoE3/TYaPTNFTGpSl7pOP3/ayqP/Tgm3O9m0Y1iR+luCfTcOaU1WuqbXq8Qj+YVP02BVvQeRbddWygCYs/7k6m4VyMACU1RKHTxDqiKM3C7UujGMAX8=

cache:
  directories:
    - node_modules

install: 'npm install'
before_script: 'snyk auth $SNYK_TOKEN'
script: 'npm test'
